# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/maysh/Desktop/project_final/project_final.cache/wt [current_project]
set_property parent.project_path C:/Users/maysh/Desktop/project_final/project_final.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/maysh/Desktop/final_project/ip_repo/cycle_1.0
  c:/Users/maysh/Desktop/final_project/ip_repo/sevenseg_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/maysh/Desktop/project_final/project_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/new/AHB2PORT1RAM.v
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/new/BRAMCtrl.v
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/new/TFTLCDCtrl.v
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/new/bin2seg.v
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/new/filter.v
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/new/g2m.v
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/new/horizontal.v
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/new/register_set.v
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/new/rgb.v
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/new/seven_seg.v
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/imports/hdl/system_wrapper.v
  C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/new/vertical.v
  C:/Users/maysh/Desktop/project_final/top.v
}
add_files C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/bd/system/ip/system_axi_ahblite_bridge_0_0/system_axi_ahblite_bridge_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/bd/system/ip/system_axi_ahblite_bridge_1_0/system_axi_ahblite_bridge_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/bd/system/system_ooc.xdc]

read_ip -quiet C:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/ip/bufferram/bufferram.xci
set_property used_in_implementation false [get_files -all c:/Users/maysh/Desktop/project_final/project_final.srcs/sources_1/ip/bufferram/bufferram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/maysh/Desktop/project_final/top.xdc
set_property used_in_implementation false [get_files C:/Users/maysh/Desktop/project_final/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
